server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    # Domain name
    server_name dzasenko.42.fr www.dzasenko.42.fr;

    # SSL certificates
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Force use of secured protocols
    ssl_protocols TLSv1.2 TLSv1.3;

    # Website root
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # PHP processing
    location ~ \.php$ {
        # include snippets/fastcgi-php.conf;
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}