services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "-c", "mysqladmin ping -u root -p$(cat /run/secrets/db_root_password) --silent"]
      interval: 5s
      retries: 10
      timeout: 5s
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WP_HOST: ${WP_HOST}
      WP_PORT: ${WP_PORT}
      WP_USER: ${WP_USER}
      WP_PASSWORD: /run/secrets/db_password
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_EDITOR: ${WP_EDITOR}
      WP_EDITOR_EMAIL: ${WP_EDITOR_EMAIL}
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "-c", "mysql -h $WP_HOST -P $WP_PORT -u $WP_USER -p$(cat /run/secrets/db_password) $MYSQL_DATABASE -e 'SHOW TABLES LIKE \"wp_options\";' | grep wp_options >/dev/null"]
      interval: 5s
      retries: 10
      timeout: 5s
      start_period: 10s

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

volumes:
  db_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: /home/${USER}/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

networks:
  inception:
    name: inception_network
    driver: bridge
